config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'my_portfolio', to: 'users#my_portfolio'
  root 'users#my_portfolio'
  get 'search_stocks', to: 'stocks#search'
  resources :user_stocks, only: [:create, :destroy]
  get 'my_friends', to: 'users#my_friends'
	resources :friendships
	resources :users, only: [:show]
  get 'search_friends', to: 'users#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks
    
	def self.new_from_lookup(ticker_symbol)
  		begin
    		looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    		price = strip_commas(looked_up_stock.l)
    		new(name: looked_up_stock.name, ticker: looked_up_stock.symbol, last_price: price)
  		rescue Exception => e
    		return nil
  		end
	end

 	def self.strip_commas(number)
  	number.gsub(",", "")
	end

  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_stocks
	has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end
  
  def under_stock_limit?
    (user_stocks.count < 10)
  end
  
  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end
  
  def self.first_name_matches(param)
    matches('first_name', param)
  end
  
  def self.last_name_matches(param)
    matches('last_name', param)
  end
  
  def self.email_matches(param)
    matches('email', param)
  end
  
  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/Users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery with: :exception
	before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	def destroy
	    @friendship = current_user.friendships.where(friend_id: params[:id]).first
	    @friendship.destroy
	    flash[:notice] = "Friend was successfully removed"
	    redirect_to my_friends_path
  	end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].blank? 
      flash.now[:danger] = "You have entered an empty search string"
    else
      @stock = Stock.new_from_lookup(params[:stock])
      flash.now[:danger] = "You have entered an incorrect symbol" unless @stock
    end
    render partial: 'users/result'
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
	def create
    	stock = Stock.find_by_ticker(params[:stock_ticker])
		    if stock.blank?
		      stock = Stock.new_from_lookup(params[:stock_ticker])
		      stock.save
		    end
	    @user_stock = UserStock.create(user: current_user, stock: stock)
	    flash[:success] = "Stock #{@user_stock.stock.name} was successfully added to portfolio"
	    redirect_to my_portfolio_path
  	end
  	def destroy
	    stock = Stock.find(params[:id])
	    @user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
	    @user_stock.destroy
	    flash[:notice] = "Stock was successfully removed from portfolio"
	    redirect_to my_portfolio_path
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@user_stocks = @user.stocks
	end
	def my_portfolio
	    @user = current_user
	    @user_stocks = current_user.stocks
  	end
  	def my_friends
   		@friendships = current_user.friends
 	end
 	def search
	   	if params[:search_param].blank?
      		flash.now[:danger] = "You have entered an empty search string"
    	else
		      @users = User.search(params[:search_param])
		      @users = current_user.except_current_user(@users)
		      flash.now[:danger] = "No users match this search criteria" if @users.blank?
    	end
	    respond_to do |format|
	      format.js { render partial: 'friends/result' }
    	end
	end
	def add_friend
	    @friend = User.find(params[:friend])
	    current_user.friendships.build(friend_id: @friend.id)
	    if current_user.save
	      flash[:notice] = "Friend was successfully added"
	    else
	      flash[:danger] = "There was something wrong with the friend request"
	    end  
	    redirect_to my_friends_path
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_lookup.html.erb
<h3>Search for Friends</h3>
<div id="friend-lookup">
  <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :search_param, params[:search_param], placeholder: "Enter name or email", autofocus: true, class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Search
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
  <%= render 'friends/result' %>
</div>

app/views/friends/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>

<% if @users %>
  <% if  @user.size > 0 %>
    <div id="friend-lookup-results" class="well results-block col-md-10">
      <table class="search-results-table col-md-12">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><strong>Name:</strong> <%= user.full_name %></td>
              <td><strong>Email:</strong> <%= user.email %></td>
              <td><strong>Profile:</strong> <%= link_to "View Profile", user_path(user), class: "btn btn-xs btn-success" %>
                <% if current_user.not_friends_with?(user.id) %>
                  <%= link_to "Add as my friend", 
                          add_friend_path(user: current_user, friend: user),
                            class: "btn btn-xs btn-success", method: :post %>
                <% else %>
                  <span class="label label-primary">
                    You are friends
                  </span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% end %>

app/views/friends/_result.js.erb
$('#results').html("<%= j (render 'friends/result.html') %>")

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <% if current_user %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Finance Tracker", root_path, class: "navbar-brand" %>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav col-md-6 ">
          <li><%= link_to "login", new_user_session_path  %></li>
          <li><%= link_to "my portfolio", my_portfolio_path  %></li>
          <li><%= link_to "My Profile", edit_registration_path(current_user) %></li>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "signup", new_user_registration_path %></li>
          <li><%= link_to "My Friends", my_friends_path  %></li>
        </ul>
        <ul class="nav navbar-right col-md-4">
          <li class="col-md-8 user-name text-right">
            <i class="fa fa-user"></i>
            <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
          </li>
          <li class="col-md-4 logout">
            <%= link_to("logout", destroy_user_session_path,
                                class: "btn btn-xs btn-danger", method: :delete) %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTracker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>