config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'my_portfolio', to: 'users#my_portfolio'
  root 'users#my_portfolio'
  get 'search_stocks', to: 'stocks#search'
  resources :user_stocks, only: [:create, :destroy]
  get 'my_friends', to: 'users#my_friends'
	resources :friendships
	resources :users, only: [:show]
  get 'search_friends', to: 'users#search'

end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_stocks
	has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end
  
  def under_stock_limit?
    (user_stocks.count < 10)
  end
  
  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end
  
  def self.first_name_matches(param)
    matches('first_name', param)
  end
  
  def self.last_name_matches(param)
    matches('last_name', param)
  end
  
  def self.email_matches(param)
    matches('email', param)
  end
  
  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
end

app/controllers/Users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
before_action :configure_permitted_parameters
   protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@user_stocks = @user.stocks
	end
	def my_portfolio
	    @user = current_user
	    @user_stocks = current_user.stocks
  	end
  	def my_friends
   		@friendships = current_user.friends
 	end
 	def search
	   	if params[:search_param].blank?
      		flash.now[:danger] = "You have entered an empty search string"
    	else
		      @users = User.search(params[:search_param])
		      @users = current_user.except_current_user(@users)
		      flash.now[:danger] = "No users match this search criteria" if @users.blank?
    	end
	    respond_to do |format|
	      format.js { render partial: 'friends/result' }
    	end
	end
	def add_friend
	    @friend = User.find(params[:friend])
	    current_user.friendships.build(friend_id: @friend.id)
	    if current_user.save
	      flash[:notice] = "Friend was successfully added"
	    else
	      flash[:danger] = "There was something wrong with the friend request"
	    end  
	    redirect_to my_friends_path
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>
  <% if @stock %>
    <div class="well results-block">
      <strong>Symbol: </strong> <%= @stock.ticker %>
      <strong>Name: </strong> <%= @stock.name %>
      <strong>Price: </strong> <%= @stock.last_price %>
    </div>
  <% end %>
  <%# if current_user.can_add_stock?(@stock.ticker) %>
   <%#= link_to "Add to my stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker), class: "btn btn-xs btn-success", method: :post %>
  <% #else %>
    <span class="label label-default">
      Stock cannot be added because you have already added
      <%# if !current_user.under_stock_limit? %>
        10 stocks
      <%# end %>
      <%# if current_user.stock_already_added?(@stock.ticker) %>
        this stock
      <% #end %>
    </span>
  <%# end %>

app/views/users/my_friends.html.erb
<%= render 'friends/lookup' %>
<% if @friendships.size > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="3" class="page-header">
          <h2>My Friends</h2>
        </th>
      </tr>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @friendships.each do |friend| %>
        <tr>
          <td><%= friend.full_name %></td>
          <td><%= friend.email %></td>
          <td>
            <%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs" %>
            <%= link_to "Remove Friend", friendship_path(friend), method: :delete,
              data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <table>  
<% else %>
  <div class="row col-lg-12">
    <p class="lead">
      You don't have any friends yet, please add some!
    </p>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<h3>Search for Stocks</h3>
<div id="stock-lookup">
  <%= form_tag search_stocks_path, method: :get, id: "stock-lookup-form" do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :stock, params[:stock],  placeholder: "Stock ticker symbol", autofocus: true, class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Look up a stock
        <% end %>
      </div>
    </div>
  
  <% end %>
</div>
<div id="results">
  <%= render 'users/result' %>
</div>
  <%= render 'stocks/list' %>

app/views/users/show.html.erb
<h2>User Details</h2> 

<dl class="dl-horizontal"> 
  <dt><strong>Full Name</strong></dt> 
  <dd><%= @user.full_name %></dd> 
  <dt><strong>Email</strong></dt> 
  <dd><%= @user.email %></dd> 
</dl> 

<% if @user.stocks.size > 0 %> 
  <%= render 'stocks/list' %> 
<% else %> 
  <p class="lead">This user is not tracking any stocks</p> 
<% end %> 

<%= link_to "Back", my_friends_path, class: "btn btn-primary" %>